server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      server-addr: 192.168.3.200:1111  #liunx上nginx代理的nacos集群地址
#      server-addr: 127.0.0.1:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*' #监控端点全部打开